### ISSUE TITLE
Make version compatible with PEP 440

### ISSUE THREAD

**Issue by bubenkoff** [xolox/python-capturer#1]
https://www.python.org/dev/peps/pep-0440/

**Comment by xolox** [comment]
Hey Anatoly and thanks for the feedback!

What about the `capturer` version scheme is incompatible with PEP 440?

The section [Examples of compliant version schemes](https://www.python.org/dev/peps/pep-0440/#examples-of-compliant-version-schemes) states that simple "major.minor" versioning and simple "major.minor.micro" versioning are both compatible. So far I've released two versions: `1.0` and `1.1`. Both fall in the simple "major.minor" version scheme, right?

Please be more verbose in your bug reports than just posting a hyperlink to a reStructuredText document of 8863 words and 60 kilobytes, I'm not psychic! ;-)

**Comment by bubenkoff** [comment]
ah, sorry, didn't know it does allow major.minor scheme as well
